- hosts: all
  gather_facts: true
  pre_tasks:
    - name: Ping
      ansible.builtin.ping:
    - name: update and upgrade all
      ansible.builtin.apt:
        upgrade: yes
        update_cache: yes
      become: true
      ignore_errors: yes
  roles:
    - role: geerlingguy.pip
      vars:
        pip_install_packages:
          - name: docker
      become: true
    # - role: geerlingguy.docker
    #   become: true
    # - role: DataDog.datadog
    #   become: true  
    #   when: 
    #     - inventory_hostname in groups["webservers"]

  tasks:
    # - name: Get running containers
    #   community.docker.docker_host_info:
    #     containers: yes
    #   register: docker_info
    #   become: true

    # - name: Stop running containers
    #   community.docker.docker_container:
    #     name: "{{ item }}"
    #     state: stopped
    #   loop: "{{ docker_info.containers | map(attribute='Id') | list }}"
    #   become: true

    - name: Delete existing dist folder
      file:
        path: /usr/src/redmine/files
        state: absent
      become: true

    - name: create redme data dir
      ansible.builtin.file:
        path: /usr/src/redmine/files
        state: directory
        # owner: "{{ansible_user}}"
        # group: "{{ansible_user}}"
        mode: '777'
      become: true

    - name: upload env file for redmine
      ansible.builtin.template:
        src: templates/redmine.env.j2
        dest: /usr/src/redmine/files/redmine.env
        # owner: "{{ansible_user}}"
        # group: "{{ansible_user}}"
        mode: '777'


    # - name: Ensure docker is in a running state
    #   ansible.builtin.service:
    #     name: docker 
    #     state: started
    #   register: dockerDetails
    #   until: dockerDetails.status.ActiveState == "active"
    #   retries: 15
    #   delay: 20
    #   become: true 

    - name: Create a redmine container
      community.docker.docker_container:
        name: app
        image: redmine:5.1.6-alpine3.21
        state: started
#        recreate: true
        restart_policy: always
        ports:
          - 80:3000
        volumes:
          - /usr/src/redmine/files:/usr/src/redmine/files
        env_file: /usr/src/redmine/files/redmine.env
      become: true
